<a href="https://colab.research.google.com/github/OmegaS48/MLDL_python/blob/main/video25_imbalanceddata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
ccd=pd.read_csv('/content/credit_data.csv')

In [4]:
ccd.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
ccd.shape

(148636, 31)

0 - legit transaction
1 - fraud

In [6]:
ccd['Class'].value_counts()

Class
0.0    148350
1.0       285
Name: count, dtype: int64

In [9]:
legit=ccd[ccd.Class==0]
print(legit)

         Time        V1        V2        V3        V4        V5        V6  \
0           0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388
1           0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361
2           1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499
3           1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203
4           2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921
...       ...       ...       ...       ...       ...       ...       ...
148630  90089 -0.625582  0.829973  1.170429  0.048991  1.112722 -0.375808
148631  90089 -1.271847 -0.305529  1.050016 -0.229606  2.046442 -1.644978
148632  90090  0.009990  0.933721  0.376333 -0.402222  0.624493 -1.008371
148633  90091  1.942382 -0.522871 -0.218608  0.497250 -0.605545  0.216448
148634  90092  2.108337  0.303093 -1.778367  0.476308  0.860514 -0.413843

              V7        V8        V9  ...       V21       V22       V23  \
0       0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474
1      -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288
2       0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412
3       0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321
4       0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458
...          ...       ...       ...  ...       ...       ...       ...
148630  0.759440 -0.209708  0.583296  ... -0.439370 -1.041486 -0.287726
148631  0.464360 -0.548854  1.143381  ... -0.383113 -0.764455 -0.057428
148632  0.931018 -0.301122  1.185722  ... -0.407501 -0.752287  0.083183
148633 -1.025009  0.216530  2.516906  ...  0.047207  0.458041  0.227490
148634  0.119543 -0.300118  1.697379  ... -0.536552 -1.145530  0.280324

             V24       V25       V26       V27       V28  Amount  Class
0       0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62    0.0
1      -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69    0.0
2      -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66    0.0
3      -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50    0.0
4       0.141267 -0.206010  0.502292  0.219422  0.215153   69.99    0.0
...          ...       ...       ...       ...       ...     ...    ...
148630 -0.750465  0.427674  0.508354 -0.046429  0.045093    9.99    0.0
148631 -0.135694 -0.317524  0.097388 -0.280328  0.064209    1.98    0.0
148632 -0.167183 -0.472779  0.107175  0.218993  0.091998    9.49    0.0
148633  0.657071 -0.389284  0.484869 -0.062182 -0.059616   11.50    0.0
148634 -0.109267 -0.196132  0.169877 -0.081930 -0.041328    1.98    0.0

[148350 rows x 31 columns]

In [10]:
fraud=ccd[ccd.Class==1]
print(fraud)

         Time        V1        V2        V3        V4        V5        V6  \
541       406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623       472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920     4462 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108     6986 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329     7519  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746
...       ...       ...       ...       ...       ...       ...       ...
144754  86376 -0.670238  0.945206  0.610051  2.640065 -2.707775  1.952611
145800  87202 -0.419820 -1.155978 -2.092516  2.786750  0.736297 -0.167292
146790  87883 -1.360293 -0.458069 -0.700404  2.737229 -1.005106  2.891399
147548  88672 -3.859881  2.632881 -5.264265  3.446113 -0.675231 -1.904959
147605  88737  1.917827  0.951967 -2.059206  3.833998  1.668192  0.769826

              V7        V8        V9  ...       V21       V22       V23  \
541    -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211
623     0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966
4920    0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726
6108   -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207
6329    1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805
...          ...       ...       ...  ...       ...       ...       ...
144754 -1.624608 -5.229908  0.210202  ... -2.504450  1.436472  0.351542
145800  1.600027 -0.117427 -0.796954  ...  0.480640  0.533517  1.284645
146790  5.802537 -1.933197 -1.017717  ... -0.936990 -0.053812  0.580106
147548 -3.291041 -0.985766 -1.168114  ...  1.664119  0.785075  0.068412
147605  0.232463  0.107941 -1.143646  ...  0.015255  0.239994 -0.111916

             V24       V25       V26       V27       V28  Amount  Class
541     0.320198  0.044519  0.177840  0.261145 -0.143276    0.00    1.0
623    -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00    1.0
4920   -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93    1.0
6108   -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00    1.0
6329   -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00    1.0
...          ...       ...       ...       ...       ...     ...    ...
144754  0.648467  0.579681  0.075738  0.346717  0.282209  323.77    1.0
145800  0.516131 -0.602941 -0.305024 -0.021363  0.129096  451.27    1.0
146790  0.216927  0.151643 -0.332115 -0.469800 -1.495006  829.41    1.0
147548  0.778961 -0.863166 -0.006810 -1.065734  1.773326    1.18    1.0
147605 -0.380576  0.370995  0.189117 -0.005823 -0.012105    9.21    1.0

[285 rows x 31 columns]

In [11]:
fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0
6108,6986,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1.0
6329,7519,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1.0

In [12]:
legit.shape
fraud.shape

(285, 31)

In [13]:
legit.shape

(148350, 31)

UnderSampling

In [17]:
#build a sample dataset mimicking this dataset's legit columns, keeping fraud the same
legitsample=legit.sample(n=285)

In [18]:
legitsample.shape

(285, 31)

In [19]:
ccd=pd.concat([legitsample,fraud],axis=0)

In [20]:
ccd

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49232,43967,-0.254925,0.864102,0.973072,0.660145,0.496296,-0.257214,1.052736,-0.249799,-0.218487,...,0.020512,0.285603,-0.187431,-0.469790,-0.118999,-0.292283,0.231077,-0.003855,49.29,0.0
100609,67567,1.105644,-1.057353,1.028122,-0.470069,-1.422332,0.042268,-0.994941,0.044381,-0.310970,...,0.415901,1.127622,-0.184765,0.180349,0.388566,-0.033062,0.054440,0.043957,118.50,0.0
36332,38491,-0.855821,0.731266,1.644628,-0.507700,1.142578,1.745453,0.509717,0.364685,-0.570406,...,-0.045234,-0.012500,-0.036601,-1.365682,-0.533174,0.150772,-0.327584,-0.134125,9.99,0.0
86140,61098,-1.246566,0.534415,-0.295123,-2.088458,2.409146,2.978434,0.172959,1.249486,-0.993775,...,-0.428931,-1.888895,0.115688,0.975968,0.160311,0.446072,-0.211777,-0.059850,58.96,0.0
112452,72654,-1.116040,0.550557,1.999201,-0.730987,1.413172,0.628691,0.659579,0.256799,-0.536558,...,-0.119218,-0.220850,-0.019244,-0.681807,-0.094851,0.038987,-0.116611,-0.158067,1.98,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144754,86376,-0.670238,0.945206,0.610051,2.640065,-2.707775,1.952611,-1.624608,-5.229908,0.210202,...,-2.504450,1.436472,0.351542,0.648467,0.579681,0.075738,0.346717,0.282209,323.77,1.0
145800,87202,-0.419820,-1.155978,-2.092516,2.786750,0.736297,-0.167292,1.600027,-0.117427,-0.796954,...,0.480640,0.533517,1.284645,0.516131,-0.602941,-0.305024,-0.021363,0.129096,451.27,1.0
146790,87883,-1.360293,-0.458069,-0.700404,2.737229,-1.005106,2.891399,5.802537,-1.933197,-1.017717,...,-0.936990,-0.053812,0.580106,0.216927,0.151643,-0.332115,-0.469800,-1.495006,829.41,1.0
147548,88672,-3.859881,2.632881,-5.264265,3.446113,-0.675231,-1.904959,-3.291041,-0.985766,-1.168114,...,1.664119,0.785075,0.068412,0.778961,-0.863166,-0.006810,-1.065734,1.773326,1.18,1.0
147605,88737,1.917827,0.951967,-2.059206,3.833998,1.668192,0.769826,0.232463,0.107941,-1.143646,...,0.015255,0.239994,-0.111916,-0.380576,0.370995,0.189117,-0.005823,-0.012105,9.21,1.0

In [21]:
ccd.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49232,43967,-0.254925,0.864102,0.973072,0.660145,0.496296,-0.257214,1.052736,-0.249799,-0.218487,...,0.020512,0.285603,-0.187431,-0.469790,-0.118999,-0.292283,0.231077,-0.003855,49.29,0.0
100609,67567,1.105644,-1.057353,1.028122,-0.470069,-1.422332,0.042268,-0.994941,0.044381,-0.310970,...,0.415901,1.127622,-0.184765,0.180349,0.388566,-0.033062,0.054440,0.043957,118.50,0.0
36332,38491,-0.855821,0.731266,1.644628,-0.507700,1.142578,1.745453,0.509717,0.364685,-0.570406,...,-0.045234,-0.012500,-0.036601,-1.365682,-0.533174,0.150772,-0.327584,-0.134125,9.99,0.0
86140,61098,-1.246566,0.534415,-0.295123,-2.088458,2.409146,2.978434,0.172959,1.249486,-0.993775,...,-0.428931,-1.888895,0.115688,0.975968,0.160311,0.446072,-0.211777,-0.059850,58.96,0.0
112452,72654,-1.116040,0.550557,1.999201,-0.730987,1.413172,0.628691,0.659579,0.256799,-0.536558,...,-0.119218,-0.220850,-0.019244,-0.681807,-0.094851,0.038987,-0.116611,-0.158067,1.98,0.0

In [22]:
ccd.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
144754,86376,-0.670238,0.945206,0.610051,2.640065,-2.707775,1.952611,-1.624608,-5.229908,0.210202,...,-2.504450,1.436472,0.351542,0.648467,0.579681,0.075738,0.346717,0.282209,323.77,1.0
145800,87202,-0.419820,-1.155978,-2.092516,2.786750,0.736297,-0.167292,1.600027,-0.117427,-0.796954,...,0.480640,0.533517,1.284645,0.516131,-0.602941,-0.305024,-0.021363,0.129096,451.27,1.0
146790,87883,-1.360293,-0.458069,-0.700404,2.737229,-1.005106,2.891399,5.802537,-1.933197,-1.017717,...,-0.936990,-0.053812,0.580106,0.216927,0.151643,-0.332115,-0.469800,-1.495006,829.41,1.0
147548,88672,-3.859881,2.632881,-5.264265,3.446113,-0.675231,-1.904959,-3.291041,-0.985766,-1.168114,...,1.664119,0.785075,0.068412,0.778961,-0.863166,-0.006810,-1.065734,1.773326,1.18,1.0
147605,88737,1.917827,0.951967,-2.059206,3.833998,1.668192,0.769826,0.232463,0.107941,-1.143646,...,0.015255,0.239994,-0.111916,-0.380576,0.370995,0.189117,-0.005823,-0.012105,9.21,1.0

In [24]:
ccd['Class'].value_counts()

Class
0.0    285
1.0    285
Name: count, dtype: int64